apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket
  labels:
    app: krateo.io
    component: socket
spec:
  replicas: 1
  selector:
    matchLabels:
      component: socket
  template:
    metadata:
      labels:
        component: socket
    spec:
      containers:
        - name: socket
          image: {{ .Values.registry.images.socket }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            timeoutSeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            timeoutSeconds: 5
            periodSeconds: 30
          envFrom:
            - configMapRef:
                name: krateo-uri-config
          env:
            - name: 'LOG_LEVEL'
              value: {{ .Values.log.level }}
      imagePullSecrets:
        - name: registry-credentials
