apiVersion: v1
kind: Service
metadata:
  name: socket-svc
  labels:
    app: krateo.io
    component: api
spec:
  selector:
    component: socket
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080